export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CATALOG_ROUTE = '/'
export const FEEDBACK_ROUTE = '/feedback'
export const CUSTOMERS_ROUTE = '/customers'
export const ORDERS_ROUTE = '/orders'
export const WAREHOUSE_ROUTE = '/warehouse'